# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0

CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_SENSOR=y


CONFIG_VL53L4CD=y
CONFIG_VL53L4CD_XSHUT=y
CONFIG_VL53L4CD_INTERRUPT_MODE=y
CONFIG_VL53L4CD_LOG_LEVEL=3
CONFIG_VL53L4CD_I2C_DETECT=n
CONFIG_VL53L4CD_I2C_FAST_MODE_PLUS=n
